### ISSUE TITLE
Using Recognition Service with more than 20k images registered

### ISSUE THREAD

**Issue by AnkurChatter** [exadel-inc/CompreFace#621]
Hi,
I tested the application and it works really amazing. 
Thank you so much for the build and documentation.
But when I upload images in excess of 1k and test the recognition services on it, the API container fails.

After that I looked into custom builds and tried mobile net/face net/insight face, all of them with no GPU support but after uploading 3k images, the container again failed during a call to recognition service for just 1 patient.
My current laptop configuration is - 
CPU - iIntel Core i3-1115G4 with 4.1 Ghz clock speed (Dual Core ) , 
OS - Win 10 64 bit, 
RAM - 8GB DDR4 2666 Mhz
Hard Disk - 1TB HDD
Graphic Card - Intel UHD Graphics 630 1666 MB

The current laptop doesn't have nvidia graphics so no additional GPU support.
**This will act as a standalone system which should be capable of using the face recognition algorithm upto a scale of 20k images. I cannot host this on cloud, need this to be on-premise**

Can you please suggest a custom build and if such a build is not possible, what kind of system configurations will be needed to scale up to that level ?

Update :- I will try running the docker container in a kubernetes cluster and see if that can help me in solving the scaling issue.

Thank you.

**Comment by pospielov** [comment]
Hi, firstly some statistics - we have a server with saved 50k images with 12Gb of RAM and it works fine.
![image](https://user-images.githubusercontent.com/3736126/135859429-c6e1bee9-3fe3-4a92-b586-d985118586c8.png)

Probably containers fail because of OOM error - they try to use more memory, but you don't have it.
But I think 8 Gb may be enough, all you need is to limit the memory that containers can use. To do this, change your .env file:
compreface_api_java_options=-Xmx3g
compreface_admin_java_options=-Xmx1g

**Comment by pospielov** [comment]
BTW if you want to run it in Kubernetes, check out this repository:
https://github.com/exadel-inc/compreface-kubernetes

**Comment by AnkurChatter** [comment]
Hi @pospielov ,

I tried the suggestion (compreface_api_java_options=-Xmx3g, compreface_admin_java_options=-Xmx1g), but the now the container is crashing even with 1k images when I try to run the recognition service.
Can you please give me your server specifications ?
My current laptop is not very high end and I have an intel graphics card(Intel UHD Graphics 630 1536 MB), not nvidia. I saw some of the env file has runtime key set as Nvidia in .env file.

Can I set the runtime to intel, if so how, can you please help/point me to a link where I can understand how to set it up ?

**Comment by pospielov** [comment]
Hi here is our hardware:
Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz 4 cores
12Gb RAM
no GPU

The question here is who is the initiator of OOM error - Linux or Java
If Linux - you can try to reduce this value even more
If Java - then you need to increase this number AND increase the RAM on your machine. 
Also, do you use Linux or Windows? Because docker under Windows requires more RAM than under Linux and this could be a problem

**Comment by pospielov** [comment]
looks like OS kills it. Try to reduce the compreface_api_java_options number to -Xmx2g

**Comment by AnkurChatter** [comment]
Sure checking now.

**Comment by AnkurChatter** [comment]
Again got killed same error.

**Comment by pospielov** [comment]
hah, is this configuration is for all containers? So 3Gb is a sum of all RAM consumption? Probably it can be not enough. Could you try 6Gb with the same configuration? 
compreface_api_java_options=-Xmx2g
compreface_admin_java_options=-Xmx1g
And yes - you don't need to redownload the images - this setup is Java runtime setup

**Comment by pospielov** [comment]
Hi, this is a bug. I already fixed it, just need to publish a hotfix. I'll try to do it today

**Comment by AnkurChatter** [comment]
Hi , I downloaded the latest version 0.6.1.
After downloading, I ran the recognition service in registration mode(registering new face).
**http://localhost:8000/api/v1/recognition/faces/?subject=Akash**
This worked and gave me a correct result.
Here is the API container log for the above
<img width="1425" alt="Screenshot 2021-10-09 at 12 53 01 PM" src="https://user-images.githubusercontent.com/8159710/136648721-f40d9502-94c8-40a7-a1f7-1e05155fbb8e.png">

**_Though the service is a little slow compared to previous version(0.6.0) in terms of how much time it takes for new registration._** (Previous was less than 1 sec, this one took 3-4 secs)

**After the registration, I ran the service in recognition mode which failed**
This is the URL - **_http://localhost:8000/api/v1/recognition/recognize_**

It was timing out most of the time. I tried checking the container logs but there was nothing there in the API container and Core container said the request was success. The CPU stats for API container went more than 200% and RAM at 2.5 GB. Core container stats was completely fine.
**Please find the error below on browser.**
<img width="830" alt="Screenshot 2021-10-09 at 12 55 19 PM" src="https://user-images.githubusercontent.com/8159710/136649073-ae098766-279e-4c97-bf33-12d316edc2ff.png">

**I feel the URL path(http://localhost:8000/api/v1/recognition/recognize) is incorrect but not sure.**  
Total RAM is 6 GB and CPU cores are 3

**Comment by AnkurChatter** [comment]
**UPDATE :-** 
I also tried testing the service through the Compreface Admin UI - 
For Demo Service - uploaded the image and waited for the service to return the result. The service was successful and got the result.
For Newly Created Service - uploaded the same image and waited for the service to return the result. The service failed with gateway timeout error.

I will create a new service(new API Key) and check what happens then.

**Comment by AnkurChatter** [comment]
**UPDATE :-**
So I created a new service and now it is working. 
Uploading images, will keep you posted on the progress.

**Comment by pospielov** [comment]
Hi
1. It's quite strange that it didn't work with the old API key, the code changes are shouldn't affect it at all and I checked the old collection on my local machine - it worked
2. I do not see any speed degradation on my machine. Probably that was only the first request which is very long because of the initialization of the libraries. 
3. What is the full error? Is it "ValueError: Your Layer or Model is in an invalid state"? If yes - I also encountered this error, looks like a bug in the new Tensorflow version, I'm investigating what we can do with it.
